import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/compoents/layout/Navbar";
import Footer from "@/compoents/layout/Footer";
import MachineMarquee from "@/compoents/MachineMarquee";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`font-sans h-full antialiased`}
    >
      <head>
        <style>
@import url('https://fonts.googleapis.com/css2?family=Clarity+City:ital,wght@0,100..900;1,100..900&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap');
</style>
      </head>
      <body className="min-h-full clarity flex flex-col">
      {/* <MachineMarquee/> */}
      <Navbar/>
        {children}
      <Footer/>
        </body>
    </html>
  );
}
